language: node_js
node_js:
- 8.11.4
after_success:
- npm run coveralls
addons:
  chrome: stable
before_script:
  - export DISPLAY=:99.0
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - sh -e /etc/init.d/xvfb start
env:
  global:
    secure: JGCH7rue//IQtv5/v7iuyNTlI/tDaxpjep9cZP+VJqBgRcWUmAOY7b0XKw0xCqlVffKsZBvyv8V1SS0BoKH40MrZ662aGkewlscvQNdKnoNDqs0905Egr95HYXW2VpOg5YVpQeoMXh4kraN4WtwRhfiWEBd391CUPMejxvyLqEFtZ4XzMZN5KEldMFs83roTS4j/l/z6CCR0OSSxrjv5AsukPgnOcUa4z6OA4Jny1cpaVeCpgd3nXeClOFitWiJybp8vkObStee0dKP4/lAxbgm21izQC2W9gsuG7Ja4hE85Nx84N3mJYol06ouxV2XW7YL13q8AC3weqZY58IsD7u+MBXNFrDxJWNdRx4TrrrIW/pgHNyetHsb8jwq0g+8JgwDqSejLewm/5rkzjuXMfwlG/WPrauFi4FZuOPeDhaFv0gBsncxVf9YGB4numo0EQukG0PAINNKfcl3GKBwDjt7tGlVWLhmMRckZVfFPniUfq+gxk91N2pE5wvpOQfCq5VVB3fH9148JvCJTirj4DXityupb8JXoLBupp4ViU9hwy8caxdaoOrSXlkq3qhjDLo3yu5Q1z2dBDnme+2btLJTzmOVEodmtkYGKVA3wxGh6eQo/Y1jEjAEpA/pEBRAnHD3N3VgykVxpr8p33GL7NhVaa+VXgPLRnG2Tu8ZmfLs=
